### ISSUE TITLE
add-path deprecation

### ISSUE THREAD

**Issue by Ergus** [conao3/setup-cask#6]
Hi:

I have been using this package and it works like a charm. But I get a deprecation warning that ptobably needs to be fixed:

```
Warning: The `add-path` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

The fix is pretty simple:

https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#example-4

**Comment by conao3** [comment]
Thanks report!
I cannot find how rewrite my code, I open an issue for [actions/toolkit](https://github.com/actions/toolkit/issues/622).

**Comment by ericdallo** [comment]
It seems that its already failiing pipelines that use that: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

@conao3 Could you take a look please? 
We have [emacs-lsp](https://github.com/emacs-lsp/lsp-mode/runs/1415582963) packages CIs failing because of that :/

**Comment by ericdallo** [comment]
I made [this workaround](https://github.com/emacs-lsp/lsp-dart/commit/b81b1eced51da99647830b829346ba2c4e1b23e0) meanwhile and it works for now.

**Comment by conao3** [comment]
Sorry for the inconvenience. I'm new at Node so I cannot understand why this action works well.
Could anyone help with this?

I move to yarn from npm on #7 and update `@actions/core` on #9 (I do `yarn install`, `yarn update`, `yarn run build`, `yarn run release`).
But the CI occurs error. Should I tag the HEAD?

**Comment by conao3** [comment]
Now, setup-cask@master is green. Please try it.

**Comment by ericdallo** [comment]
Thanks, I'll try to change CI soon

**Comment by rnikoopour** [comment]
I was reviewing how https://github.com/purcell/setup-emacs works.  It looks like they are invoking a script from the runner to do the installation instead of doing the entire install via JavaScript:

https://github.com/purcell/setup-emacs/blob/master/src/installNix.ts#L5

In the script it looks like they add to their binary paths to `$GITHUB_PATH` ([docs](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#adding-a-system-path)):
https://github.com/purcell/setup-emacs/blob/master/dist/install-nix.sh#L42-L44

Could a similar approach be taken here to remove the `addPath` dependency?  

Or perhaps the `$GITHUB_PATH` file could be appended to via JavaScript?

**Comment by ericdallo** [comment]
It seems a valid approach for me.
Anyway, the master now is working, I think we can close this, thank you!

**Comment by conao3** [comment]
Thanks, I'll close this as I'm sure it's working well in other environments.
